baseURL = "http://sijakubo.de/"

# Change the default theme to be used when building the site with Hugo
theme = "LoveIt"

# Website title
title = "Simon Jakubowski"

# Language settings
languageCode = "de"
languageName = "Detusch"

# Menu config
[menu]
  [[menu.main]]
  weight = 1
  identifier = "posts"
  pre = ""   # Extra information before the name (HTML supported)
  post = ""  # Extra information after the name (HTML supported)
  name = "Posts"
  url = "/posts/"
  title = "" # Title shown on hover

[[menu.main]]
  weight = 2
  identifier = "tags"
  pre = ""
  post = ""
  name = "Tags"
  url = "/tags/"
  title = ""

[[menu.main]]
  weight = 3
  identifier = "about"
  pre = ""
  post = ""
  name = "About"
  url = "/about/"
  title = ""

# Markup related configuration in Hugo
[markup]

  # Syntax Highlighting (https://gohugo.io/content-management/syntax-highlighting)
  [markup.highlight]
  noClasses = false  # Required for compatibility (https://github.com/dillonzq/LoveIt/issues/158)

[params]
  title = "Simon Jakubowski"
  description = "About Simon Jakubowski"
  [params.author]
    name = " Simon Jakubowski"
    email = "sijakubo@gmail.com"
    link = ""
  [params.social]
    GitHub = "sijakubo"
    Linkedin = "simon-jakubowski"

# Output formats
[outputs]
  home = ["HTML", "RSS", "JSON"]
  page = ["HTML", "MarkDown"]
  section = ["HTML", "RSS"]
  taxonomy = ["HTML", "RSS"]

[caches]
  [caches.images]
    dir = ':cacheDir/images'
